### ISSUE TITLE
1.0 Release - ToDo

### ISSUE THREAD

**Issue by AlexanderEggers** [AlexanderEggers/archtree#8]
### General
- [x] Remove core artifact
- [ ] Add Javadoc to all public methods/classes.

### Builder Artifact
- [x] Parse the default bundle object of Activity/Fragment to ViewModel.
- [x] Add support for android navigation lib (Main issue is accessing the current fragments: https://stackoverflow.com/questions/51385067/android-navigation-architecture-component-get-current-visible-fragment)

### Helper Artifact
- [x] Refactore artifact structure: Helper-Core and Helper-ArchKnife. Core has all classes but has no reference to dagger. ArchKnife is using the helper classes to provide these to a Module class that can be added to the dev's dependency graph. That should improve the usage of this artifact and also allow adding more helper classes in the future.

 ### List Artifact
- [x] Add new methods to handle adapter list item/view creation. Therefore one item can be based on x sub-items which define the actual item (having their own binding method etc.)
